<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="governanceapi" nsURI="http://datainmotion.com/mac/governance/api/1.0.0"
    nsPrefix="govapi">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="modelName" value="ManagementApi"/>
    <details key="complianceLevel" value="17.0"/>
    <details key="copyrightText" value="Copyright (c) 2012 - 2025 Data In Motion and others.&#xA;All rights reserved.&#xA;&#xA;This program and the accompanying materials are made&#xA;available under the terms of the Eclipse Public License 2.0&#xA;which is available at https://www.eclipse.org/legal/epl-2.0/&#xA;&#xA;SPDX-License-Identifier: EPL-2.0&#xA;&#xA;Contributors:&#xA;     Mark Hoffmann - initial API and implementation"/>
    <details key="resource" value="XMI"/>
    <details key="prefix" value="ManagementApi"/>
    <details key="basePackage" value="org.gecko.mac.mgmt"/>
    <details key="rootExtendsInterface" value=""/>
    <details key="oSGiCompatible" value="true"/>
    <details key="suppressNotification" value="true"/>
    <details key="suppressEMFTypes" value="true"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectWorkflowService" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Generic orchestrator for EObject workflow management"/>
    </eAnnotations>
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eOperations name="approveObject" eType="ecore:EClass ../../org.gecko.mac.management/model/management.ecore#//ObjectMetadata">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Approve an object for release, returns updated registration"/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="approvalReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="rejectObject" eType="ecore:EClass ../../org.gecko.mac.management/model/management.ecore#//ObjectMetadata">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reject an object during review, returns updated registration"/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="rejectionReason" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="releaseObject" eType="ecore:EClass ../../org.gecko.mac.management/model/management.ecore#//ObjectMetadata">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Release an approved object to production storage after compliance checks, returns updated registration"/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="releaseNotes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="requireComplianceCheck" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="listApprovedObjects">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List all approved objects ready for release"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//List">
        <eTypeArguments eClassifier="ecore:EClass ../../org.gecko.mac.management/model/management.ecore#//ObjectMetadata"/>
      </eGenericType>
    </eOperations>
    <eOperations name="listRejectedObjects">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List all rejected objects"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//List">
        <eTypeArguments eClassifier="ecore:EClass ../../org.gecko.mac.management/model/management.ecore#//ObjectMetadata"/>
      </eGenericType>
    </eOperations>
    <eOperations name="listReleasedObjects">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List all released/production objects"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//List">
        <eTypeArguments eClassifier="ecore:EClass ../../org.gecko.mac.management/model/management.ecore#//ObjectMetadata"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getObject" eType="ecore:EClass ../../org.gecko.mac.management/model/management.ecore#//ObjectMetadata">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get object registration by ID"/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getObjectContent" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get the actual EObject content by ID"/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="updateObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Update an existing object"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Void"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="updatedObject" lowerBound="1">
        <eGenericType eTypeParameter="#//EObjectWorkflowService/T"/>
      </eParameters>
    </eOperations>
    <eOperations name="deleteObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Delete an object"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="#//WorkflowDraftProvider">
      <eTypeArguments eTypeParameter="#//EObjectWorkflowService/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//WorkflowComplianceProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemComponentGovernanceService" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Service for managing governance of system components within a specific GovernanceSystem. Each service instance is scoped to a single system for isolation and security."/>
    </eAnnotations>
    <eOperations name="registerSystemComponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Register a new system component in the governance framework"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//SystemComponent"/>
      </eGenericType>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="componentType" lowerBound="1" eType="ecore:EEnum governance.ecore#//SystemComponentType"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="updateSystemComponentTrustLevel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Update the trust level of a system component"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//SystemComponent"/>
      </eGenericType>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="trustLevel" lowerBound="1" eType="ecore:EEnum governance.ecore#//TrustLevel"/>
    </eOperations>
    <eOperations name="runSystemComponentCompliance">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Run compliance checks on a system component for specified policies"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//GovernanceDocumentation"/>
      </eGenericType>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="policyTypes" upperBound="-1" eType="ecore:EEnum governance.ecore#//PolicyType"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="applyPoliciesToSystemComponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Apply policies to a system component"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Void"/>
      </eGenericType>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="policyIds" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getSystemComponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get system component by ID"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//SystemComponent"/>
      </eGenericType>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findSystemComponentsByGovernanceStatus">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Find system components by governance compliance status"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//List">
          <eTypeArguments eClassifier="ecore:EClass governance.ecore#//SystemComponent"/>
        </eTypeArguments>
      </eGenericType>
      <eParameters name="complianceStatus" lowerBound="1" eType="ecore:EEnum governance.ecore#//ComplianceStatus"/>
    </eOperations>
    <eOperations name="linkModelToSystemComponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Link an EObject (like generated EPackage) to its source system component"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Void"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getSystemComponentsByType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get all system components of a specific type"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//List">
          <eTypeArguments eClassifier="ecore:EClass governance.ecore#//SystemComponent"/>
        </eTypeArguments>
      </eGenericType>
      <eParameters name="componentType" lowerBound="1" eType="ecore:EEnum governance.ecore#//SystemComponentType"/>
    </eOperations>
    <eOperations name="getSystemId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get the system ID this service instance is managing"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GovernanceComplianceService" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Service for running governance compliance checks and managing compliance documentation. This service orchestrates various policy-specific compliance checks and generates comprehensive governance documentation."/>
    </eAnnotations>
    <eOperations name="runComplianceChecks">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Run comprehensive compliance checks on an object for all applicable policies"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//GovernanceDocumentation"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="complianceReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="runSpecificComplianceChecks">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Run specific compliance checks for given policy types"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//GovernanceDocumentation"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="policyTypes" upperBound="-1" eType="ecore:EEnum governance.ecore#//PolicyType"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="runSystemComponentCompliance">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Run compliance checks specifically for system components"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//GovernanceDocumentation"/>
      </eGenericType>
      <eParameters name="systemId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="policyTypes" upperBound="-1" eType="ecore:EEnum governance.ecore#//PolicyType"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getComplianceStatus">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get the current compliance status and documentation for an object"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//GovernanceDocumentation"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="validatePolicyCompliance">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Validate compliance for a specific policy without storing results"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//ComplianceCheckResult"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="policyType" lowerBound="1" eType="ecore:EEnum governance.ecore#//PolicyType"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getAvailablePolicies">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get list of all available policy types for compliance checking"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//List">
        <eTypeArguments eClassifier="ecore:EEnum governance.ecore#//PolicyType"/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GovernanceSystemRepository" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Repository interface for managing governance systems and system components. This interface abstracts the storage and retrieval of governance-related entities."/>
    </eAnnotations>
    <eOperations name="getGovernanceSystem" eType="ecore:EClass governance.ecore#//GovernanceSystem">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get a governance system by ID"/>
      </eAnnotations>
      <eParameters name="systemId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createSystemComponent" eType="ecore:EClass governance.ecore#//SystemComponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Create a new system component"/>
      </eAnnotations>
      <eParameters name="systemId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="componentType" lowerBound="1" eType="ecore:EEnum governance.ecore#//SystemComponentType"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getSystemComponent" eType="ecore:EClass governance.ecore#//SystemComponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get a system component by ID within a specific system"/>
      </eAnnotations>
      <eParameters name="systemId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="updateSystemComponentTrustLevel" eType="ecore:EClass governance.ecore#//SystemComponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Update the trust level of a system component"/>
      </eAnnotations>
      <eParameters name="systemId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="trustLevel" lowerBound="1" eType="ecore:EEnum governance.ecore#//TrustLevel"/>
    </eOperations>
    <eOperations name="applyPoliciesToSystemComponent" eType="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Void">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Apply policies to a system component"/>
      </eAnnotations>
      <eParameters name="systemId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="policyIds" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findSystemComponentsByComplianceStatus">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Find system components by compliance status"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//List">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//SystemComponent"/>
      </eGenericType>
      <eParameters name="systemId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="complianceStatus" lowerBound="1" eType="ecore:EEnum governance.ecore#//ComplianceStatus"/>
    </eOperations>
    <eOperations name="getSystemComponentsByType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get system components by type"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//List">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//SystemComponent"/>
      </eGenericType>
      <eParameters name="systemId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="componentType" lowerBound="1" eType="ecore:EEnum governance.ecore#//SystemComponentType"/>
    </eOperations>
    <eOperations name="linkModelToSystemComponent" eType="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Void">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Link a model object to its source system component"/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="systemId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="componentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemComponentGovernanceConfig" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Configuration interface for SystemComponentGovernanceService factory instances"/>
    </eAnnotations>
    <eOperations name="systemId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The system ID this service instance manages"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Optional description of the governance system"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowDraftProvider" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Generic orchestrator for EObject workflow management"/>
    </eAnnotations>
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eOperations name="uploadDraft">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Upload an EObject to draft storage for review, returns promise with object ID"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
      <eParameters name="object" lowerBound="1">
        <eGenericType eTypeParameter="#//WorkflowDraftProvider/T"/>
      </eParameters>
      <eParameters name="metadata" lowerBound="1" eType="ecore:EClass ../../org.gecko.mac.management/model/management.ecore#//ObjectMetadata"/>
    </eOperations>
    <eOperations name="listDraftObjects">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List all objects in draft/review status"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//List">
        <eTypeArguments eClassifier="ecore:EClass ../../org.gecko.mac.management/model/management.ecore#//ObjectMetadata"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getDraft" eType="ecore:EClass ../../org.gecko.mac.management/model/management.ecore#//ObjectMetadata">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get object registration by ID"/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getDraftContent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get the actual EObject content by ID"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//WorkflowDraftProvider/T"/>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="updateDraft">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Update an existing object"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Void"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="updatedObject" lowerBound="1">
        <eGenericType eTypeParameter="#//WorkflowDraftProvider/T"/>
      </eParameters>
    </eOperations>
    <eOperations name="deleteDraft">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Delete an object"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="checkDraft">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Run comprehensive governance compliance checks on an object, returns documentation with check results"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//GovernanceDocumentation"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="complianceReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowComplianceProvider" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Generic orchestrator for EObject workflow management"/>
    </eAnnotations>
    <eOperations name="checkObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Run comprehensive governance compliance checks on an object, returns documentation with check results"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//GovernanceDocumentation"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="complianceReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="runComplianceChecks">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Run specific compliance checks on an object for given policy types"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//GovernanceDocumentation"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="policyTypes" upperBound="-1" eType="ecore:EEnum governance.ecore#//PolicyType"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getComplianceStatus" eType="ecore:EClass governance.ecore#//GovernanceDocumentation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get the current compliance status for an object"/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="setGovernanceDocumentationDraft" eType="ecore:EClass governance.ecore#//GovernanceDocumentation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set governance documentation status to DRAFT with audit trail. Valid transitions: Any state → DRAFT (allows resetting to draft for rework). This operation is typically used when creating new governance documentation or when returning documentation for rework after rejection."/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="setGovernanceDocumentationInReview" eType="ecore:EClass governance.ecore#//GovernanceDocumentation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set governance documentation status to IN_REVIEW with audit trail. Valid transitions: DRAFT → IN_REVIEW, REJECTED → IN_REVIEW (allows resubmission after addressing rejection feedback). Cannot transition from APPROVED to IN_REVIEW without first returning to DRAFT."/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="setGovernanceDocumentationApproved" eType="ecore:EClass governance.ecore#//GovernanceDocumentation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set governance documentation status to APPROVED with audit trail. Valid transitions: IN_REVIEW → APPROVED (normal approval path). This is the terminal state that enables object approval in the governance-gated workflow. Once approved, governance documentation enables the parent object to be approved for release."/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="setGovernanceDocumentationRejected" eType="ecore:EClass governance.ecore#//GovernanceDocumentation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set governance documentation status to REJECTED with audit trail. Valid transitions: IN_REVIEW → REJECTED (when compliance review fails). From REJECTED state, documentation can be returned to DRAFT for rework or resubmitted to IN_REVIEW after addressing issues. Rejected governance documentation blocks object approval until resolved."/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GovernanceDocumentationService" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Service for managing governance documentation storage and retrieval. Provides dedicated storage for governance documentation independent of object lifecycle with versioned storage, history tracking, and fast lookup capabilities."/>
    </eAnnotations>
    <eOperations name="storeDocumentation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Store governance documentation for an object. Creates both versioned and latest documentation entries for comprehensive audit trail and fast access. The reason parameter is stored in the ObjectMetadata reviewReason field for audit purposes."/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="documentation" lowerBound="1" eType="ecore:EClass governance.ecore#//GovernanceDocumentation"/>
      <eParameters name="reviewUser" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getLatestDocumentation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Retrieve the latest governance documentation for an object"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Optional">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//GovernanceDocumentation"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getDocumentation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Retrieve specific governance documentation by its ID"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Optional">
        <eTypeArguments eClassifier="ecore:EClass governance.ecore#//GovernanceDocumentation"/>
      </eGenericType>
      <eParameters name="documentationId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getDocumentationHistory">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get the governance documentation history for an object, returning all versioned documentation ordered by creation time"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//List">
        <eTypeArguments eClassifier="ecore:EClass ../../org.gecko.mac.management/model/management.ecore#//ObjectMetadata"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="hasDocumentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check if governance documentation exists for an object"/>
      </eAnnotations>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="deleteAllDocumentation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Delete all governance documentation for an object. Removes both versioned and latest documentation. Use with caution as this destroys the compliance audit trail."/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType ../../org.gecko.mac.management/model/management.ecore#//Promise">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eGenericType>
      <eParameters name="objectId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getDocumentationStatistics">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get governance documentation statistics including total documentation count, active objects, and historical compliance check metrics"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
