/*
 * Copyright (c) 2012 - 2025 Data In Motion and others.
 * All rights reserved.
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *      Mark Hoffmann - initial API and implementation
 */
package org.eclipse.fennec.model.atlas.governance;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.osgi.annotation.versioning.ProviderType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Documentation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * Represents the complete documentation for a specific data model version, generated as the result of a governance workflow.
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getModelName <em>Model Name</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getVersion <em>Version</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getStatus <em>Status</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getGenerationTimestamp <em>Generation Timestamp</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getApprovedBy <em>Approved By</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getDescription <em>Description</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getDataOwner <em>Data Owner</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getDataClassification <em>Data Classification</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getComplianceChecks <em>Compliance Checks</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getSourceSystemComponent <em>Source System Component</em>}</li>
 * </ul>
 *
 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation()
 * @model
 * @generated
 */
@ProviderType
public interface GovernanceDocumentation extends EObject {
	/**
	 * Returns the value of the '<em><b>Model Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Model Name</em>' attribute.
	 * @see #setModelName(String)
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_ModelName()
	 * @model
	 * @generated
	 */
	String getModelName();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getModelName <em>Model Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Model Name</em>' attribute.
	 * @see #getModelName()
	 * @generated
	 */
	void setModelName(String value);

	/**
	 * Returns the value of the '<em><b>Version</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Version</em>' attribute.
	 * @see #setVersion(String)
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_Version()
	 * @model
	 * @generated
	 */
	String getVersion();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getVersion <em>Version</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Version</em>' attribute.
	 * @see #getVersion()
	 * @generated
	 */
	void setVersion(String value);

	/**
	 * Returns the value of the '<em><b>Status</b></em>' attribute.
	 * The literals are from the enumeration {@link org.eclipse.fennec.model.atlas.governance.ApprovalStatus}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Status</em>' attribute.
	 * @see org.eclipse.fennec.model.atlas.governance.ApprovalStatus
	 * @see #setStatus(ApprovalStatus)
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_Status()
	 * @model
	 * @generated
	 */
	ApprovalStatus getStatus();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getStatus <em>Status</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Status</em>' attribute.
	 * @see org.eclipse.fennec.model.atlas.governance.ApprovalStatus
	 * @see #getStatus()
	 * @generated
	 */
	void setStatus(ApprovalStatus value);

	/**
	 * Returns the value of the '<em><b>Generation Timestamp</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Generation Timestamp</em>' attribute.
	 * @see #setGenerationTimestamp(Date)
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_GenerationTimestamp()
	 * @model
	 * @generated
	 */
	Date getGenerationTimestamp();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getGenerationTimestamp <em>Generation Timestamp</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generation Timestamp</em>' attribute.
	 * @see #getGenerationTimestamp()
	 * @generated
	 */
	void setGenerationTimestamp(Date value);

	/**
	 * Returns the value of the '<em><b>Generated By</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Generated By</em>' attribute.
	 * @see #setGeneratedBy(String)
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_GeneratedBy()
	 * @model
	 * @generated
	 */
	String getGeneratedBy();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getGeneratedBy <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generated By</em>' attribute.
	 * @see #getGeneratedBy()
	 * @generated
	 */
	void setGeneratedBy(String value);

	/**
	 * Returns the value of the '<em><b>Approved By</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Approved By</em>' attribute.
	 * @see #setApprovedBy(String)
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_ApprovedBy()
	 * @model
	 * @generated
	 */
	String getApprovedBy();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getApprovedBy <em>Approved By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Approved By</em>' attribute.
	 * @see #getApprovedBy()
	 * @generated
	 */
	void setApprovedBy(String value);

	/**
	 * Returns the value of the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Description</em>' attribute.
	 * @see #setDescription(String)
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_Description()
	 * @model
	 * @generated
	 */
	String getDescription();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getDescription <em>Description</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Description</em>' attribute.
	 * @see #getDescription()
	 * @generated
	 */
	void setDescription(String value);

	/**
	 * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.fennec.model.atlas.governance.AttributeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Attributes</em>' containment reference list.
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_Attributes()
	 * @model containment="true"
	 * @generated
	 */
	EList<AttributeDefinition> getAttributes();

	/**
	 * Returns the value of the '<em><b>Data Owner</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Data Owner</em>' attribute.
	 * @see #setDataOwner(String)
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_DataOwner()
	 * @model
	 * @generated
	 */
	String getDataOwner();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getDataOwner <em>Data Owner</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Data Owner</em>' attribute.
	 * @see #getDataOwner()
	 * @generated
	 */
	void setDataOwner(String value);

	/**
	 * Returns the value of the '<em><b>Data Classification</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Data Classification</em>' attribute.
	 * @see #setDataClassification(String)
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_DataClassification()
	 * @model
	 * @generated
	 */
	String getDataClassification();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getDataClassification <em>Data Classification</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Data Classification</em>' attribute.
	 * @see #getDataClassification()
	 * @generated
	 */
	void setDataClassification(String value);

	/**
	 * Returns the value of the '<em><b>Compliance Checks</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.fennec.model.atlas.governance.ComplianceCheckResult}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Compliance Checks</em>' containment reference list.
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_ComplianceChecks()
	 * @model containment="true"
	 * @generated
	 */
	EList<ComplianceCheckResult> getComplianceChecks();

	/**
	 * Returns the value of the '<em><b>Source System Component</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Source System Component</em>' attribute.
	 * @see #setSourceSystemComponent(String)
	 * @see org.eclipse.fennec.model.atlas.governance.GovernancePackage#getGovernanceDocumentation_SourceSystemComponent()
	 * @model
	 * @generated
	 */
	String getSourceSystemComponent();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation#getSourceSystemComponent <em>Source System Component</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Source System Component</em>' attribute.
	 * @see #getSourceSystemComponent()
	 * @generated
	 */
	void setSourceSystemComponent(String value);

} // GovernanceDocumentation
