<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dinspec91377" nsURI="https://datainmotion.com/mac/policy/din_spec_91377/1.0.0"
    nsPrefix="dinspec91377">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="modelName" value="DINSPEC91377Policy"/>
    <details key="complianceLevel" value="17.0"/>
    <details key="copyrightText" value="Copyright (c) 2012 - 2025 Data In Motion and others.&#xA;All rights reserved.&#xA;&#xA;This program and the accompanying materials are made&#xA;available under the terms of the Eclipse Public License 2.0&#xA;which is available at https://www.eclipse.org/legal/epl-2.0/&#xA;&#xA;SPDX-License-Identifier: EPL-2.0&#xA;&#xA;Contributors:&#xA;     Mark Hoffmann - initial API and implementation"/>
    <details key="resource" value="XMI"/>
    <details key="oSGiCompatible" value="true"/>
    <details key="prefix" value="DS91377"/>
    <details key="basePackage" value="org.gecko.mac.policy"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DINSPEC91377PolicyCheck" eSuperTypes="../governance.ecore#//ComplianceCheckResult">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A specialized compliance check that represents the verification against key requirements of the DIN SPEC 91377 for Open Urban Platforms (OUP)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="architectureLayersImplemented"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check result (Chapter 4.5): Is the OUP core structured according to the specified horizontal (Interfaces, Processing, Integration) and vertical (Management) layers?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelCentricDataFlowApplied"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check result (Chapter 4.6): Does the platform follow the model-centric data flow concept, using a Model and Data Flow Management (MDM) component to configure its software modules?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interfaceInteroperabilityEnsured"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check result (Chapter 5.3): Does the Interfaces Layer utilize standardized connectors and protocols (e.g., OGC API, MQTT) for inbound data?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integrationApiStandardsMet"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check result (Chapter 5.5): Does the Integration Layer provide open, standardized APIs (e.g., OGC API Features, SensorThings API) for outbound data?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managementServicesProvided"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check result (Chapter 5.6): Does the Management Layer provide the required core services, including IAM (OIDC/SAML), a DCAT-AP compliant Data Catalog, and API Management?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="informationSecurityConceptApplied"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check result (Chapter 6): Is a holistic information security concept applied, covering data security (confidentiality, integrity, availability), IAM, and secure communication (TLS)?"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
