/*
 * Copyright (c) 2012 - 2025 Data In Motion and others.
 * All rights reserved.
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *      Mark Hoffmann - initial API and implementation
 */
package org.eclipse.fennec.model.atlas.governance.impl;

import java.util.Collection;
import java.util.Date;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.eclipse.fennec.model.atlas.governance.ApprovalStatus;
import org.eclipse.fennec.model.atlas.governance.AttributeDefinition;
import org.eclipse.fennec.model.atlas.governance.ComplianceCheckResult;
import org.eclipse.fennec.model.atlas.governance.GovernanceDocumentation;
import org.eclipse.fennec.model.atlas.governance.GovernancePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Documentation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getModelName <em>Model Name</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getVersion <em>Version</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getStatus <em>Status</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getGenerationTimestamp <em>Generation Timestamp</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getApprovedBy <em>Approved By</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getDataOwner <em>Data Owner</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getDataClassification <em>Data Classification</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getComplianceChecks <em>Compliance Checks</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.atlas.governance.impl.GovernanceDocumentationImpl#getSourceSystemComponent <em>Source System Component</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GovernanceDocumentationImpl extends MinimalEObjectImpl.Container implements GovernanceDocumentation {
	/**
	 * The default value of the '{@link #getModelName() <em>Model Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getModelName()
	 * @generated
	 * @ordered
	 */
	protected static final String MODEL_NAME_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getModelName() <em>Model Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getModelName()
	 * @generated
	 * @ordered
	 */
	protected String modelName = MODEL_NAME_EDEFAULT;

	/**
	 * The default value of the '{@link #getVersion() <em>Version</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getVersion()
	 * @generated
	 * @ordered
	 */
	protected static final String VERSION_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getVersion() <em>Version</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getVersion()
	 * @generated
	 * @ordered
	 */
	protected String version = VERSION_EDEFAULT;

	/**
	 * The default value of the '{@link #getStatus() <em>Status</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getStatus()
	 * @generated
	 * @ordered
	 */
	protected static final ApprovalStatus STATUS_EDEFAULT = ApprovalStatus.DRAFT;

	/**
	 * The cached value of the '{@link #getStatus() <em>Status</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getStatus()
	 * @generated
	 * @ordered
	 */
	protected ApprovalStatus status = STATUS_EDEFAULT;

	/**
	 * The default value of the '{@link #getGenerationTimestamp() <em>Generation Timestamp</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGenerationTimestamp()
	 * @generated
	 * @ordered
	 */
	protected static final Date GENERATION_TIMESTAMP_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGenerationTimestamp() <em>Generation Timestamp</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGenerationTimestamp()
	 * @generated
	 * @ordered
	 */
	protected Date generationTimestamp = GENERATION_TIMESTAMP_EDEFAULT;

	/**
	 * The default value of the '{@link #getGeneratedBy() <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATED_BY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGeneratedBy() <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected String generatedBy = GENERATED_BY_EDEFAULT;

	/**
	 * The default value of the '{@link #getApprovedBy() <em>Approved By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getApprovedBy()
	 * @generated
	 * @ordered
	 */
	protected static final String APPROVED_BY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getApprovedBy() <em>Approved By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getApprovedBy()
	 * @generated
	 * @ordered
	 */
	protected String approvedBy = APPROVED_BY_EDEFAULT;

	/**
	 * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDescription()
	 * @generated
	 * @ordered
	 */
	protected static final String DESCRIPTION_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDescription()
	 * @generated
	 * @ordered
	 */
	protected String description = DESCRIPTION_EDEFAULT;

	/**
	 * The cached value of the '{@link #getAttributes() <em>Attributes</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getAttributes()
	 * @generated
	 * @ordered
	 */
	protected EList<AttributeDefinition> attributes;

	/**
	 * The default value of the '{@link #getDataOwner() <em>Data Owner</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDataOwner()
	 * @generated
	 * @ordered
	 */
	protected static final String DATA_OWNER_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getDataOwner() <em>Data Owner</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDataOwner()
	 * @generated
	 * @ordered
	 */
	protected String dataOwner = DATA_OWNER_EDEFAULT;

	/**
	 * The default value of the '{@link #getDataClassification() <em>Data Classification</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDataClassification()
	 * @generated
	 * @ordered
	 */
	protected static final String DATA_CLASSIFICATION_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getDataClassification() <em>Data Classification</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDataClassification()
	 * @generated
	 * @ordered
	 */
	protected String dataClassification = DATA_CLASSIFICATION_EDEFAULT;

	/**
	 * The cached value of the '{@link #getComplianceChecks() <em>Compliance Checks</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getComplianceChecks()
	 * @generated
	 * @ordered
	 */
	protected EList<ComplianceCheckResult> complianceChecks;

	/**
	 * The default value of the '{@link #getSourceSystemComponent() <em>Source System Component</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSourceSystemComponent()
	 * @generated
	 * @ordered
	 */
	protected static final String SOURCE_SYSTEM_COMPONENT_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getSourceSystemComponent() <em>Source System Component</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSourceSystemComponent()
	 * @generated
	 * @ordered
	 */
	protected String sourceSystemComponent = SOURCE_SYSTEM_COMPONENT_EDEFAULT;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GovernanceDocumentationImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return GovernancePackage.Literals.GOVERNANCE_DOCUMENTATION;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getModelName() {
		return modelName;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setModelName(String newModelName) {
		String oldModelName = modelName;
		modelName = newModelName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GovernancePackage.GOVERNANCE_DOCUMENTATION__MODEL_NAME, oldModelName, modelName));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getVersion() {
		return version;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setVersion(String newVersion) {
		String oldVersion = version;
		version = newVersion;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GovernancePackage.GOVERNANCE_DOCUMENTATION__VERSION, oldVersion, version));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ApprovalStatus getStatus() {
		return status;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setStatus(ApprovalStatus newStatus) {
		ApprovalStatus oldStatus = status;
		status = newStatus == null ? STATUS_EDEFAULT : newStatus;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GovernancePackage.GOVERNANCE_DOCUMENTATION__STATUS, oldStatus, status));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Date getGenerationTimestamp() {
		return generationTimestamp;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGenerationTimestamp(Date newGenerationTimestamp) {
		Date oldGenerationTimestamp = generationTimestamp;
		generationTimestamp = newGenerationTimestamp;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GovernancePackage.GOVERNANCE_DOCUMENTATION__GENERATION_TIMESTAMP, oldGenerationTimestamp, generationTimestamp));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getGeneratedBy() {
		return generatedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedBy(String newGeneratedBy) {
		String oldGeneratedBy = generatedBy;
		generatedBy = newGeneratedBy;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GovernancePackage.GOVERNANCE_DOCUMENTATION__GENERATED_BY, oldGeneratedBy, generatedBy));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getApprovedBy() {
		return approvedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setApprovedBy(String newApprovedBy) {
		String oldApprovedBy = approvedBy;
		approvedBy = newApprovedBy;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GovernancePackage.GOVERNANCE_DOCUMENTATION__APPROVED_BY, oldApprovedBy, approvedBy));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getDescription() {
		return description;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setDescription(String newDescription) {
		String oldDescription = description;
		description = newDescription;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GovernancePackage.GOVERNANCE_DOCUMENTATION__DESCRIPTION, oldDescription, description));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<AttributeDefinition> getAttributes() {
		if (attributes == null) {
			attributes = new EObjectContainmentEList<AttributeDefinition>(AttributeDefinition.class, this, GovernancePackage.GOVERNANCE_DOCUMENTATION__ATTRIBUTES);
		}
		return attributes;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getDataOwner() {
		return dataOwner;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setDataOwner(String newDataOwner) {
		String oldDataOwner = dataOwner;
		dataOwner = newDataOwner;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GovernancePackage.GOVERNANCE_DOCUMENTATION__DATA_OWNER, oldDataOwner, dataOwner));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getDataClassification() {
		return dataClassification;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setDataClassification(String newDataClassification) {
		String oldDataClassification = dataClassification;
		dataClassification = newDataClassification;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GovernancePackage.GOVERNANCE_DOCUMENTATION__DATA_CLASSIFICATION, oldDataClassification, dataClassification));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<ComplianceCheckResult> getComplianceChecks() {
		if (complianceChecks == null) {
			complianceChecks = new EObjectContainmentEList<ComplianceCheckResult>(ComplianceCheckResult.class, this, GovernancePackage.GOVERNANCE_DOCUMENTATION__COMPLIANCE_CHECKS);
		}
		return complianceChecks;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getSourceSystemComponent() {
		return sourceSystemComponent;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setSourceSystemComponent(String newSourceSystemComponent) {
		String oldSourceSystemComponent = sourceSystemComponent;
		sourceSystemComponent = newSourceSystemComponent;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GovernancePackage.GOVERNANCE_DOCUMENTATION__SOURCE_SYSTEM_COMPONENT, oldSourceSystemComponent, sourceSystemComponent));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__ATTRIBUTES:
				return ((InternalEList<?>)getAttributes()).basicRemove(otherEnd, msgs);
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__COMPLIANCE_CHECKS:
				return ((InternalEList<?>)getComplianceChecks()).basicRemove(otherEnd, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__MODEL_NAME:
				return getModelName();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__VERSION:
				return getVersion();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__STATUS:
				return getStatus();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__GENERATION_TIMESTAMP:
				return getGenerationTimestamp();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__GENERATED_BY:
				return getGeneratedBy();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__APPROVED_BY:
				return getApprovedBy();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DESCRIPTION:
				return getDescription();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__ATTRIBUTES:
				return getAttributes();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DATA_OWNER:
				return getDataOwner();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DATA_CLASSIFICATION:
				return getDataClassification();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__COMPLIANCE_CHECKS:
				return getComplianceChecks();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__SOURCE_SYSTEM_COMPONENT:
				return getSourceSystemComponent();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__MODEL_NAME:
				setModelName((String)newValue);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__VERSION:
				setVersion((String)newValue);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__STATUS:
				setStatus((ApprovalStatus)newValue);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__GENERATION_TIMESTAMP:
				setGenerationTimestamp((Date)newValue);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__GENERATED_BY:
				setGeneratedBy((String)newValue);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__APPROVED_BY:
				setApprovedBy((String)newValue);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DESCRIPTION:
				setDescription((String)newValue);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__ATTRIBUTES:
				getAttributes().clear();
				getAttributes().addAll((Collection<? extends AttributeDefinition>)newValue);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DATA_OWNER:
				setDataOwner((String)newValue);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DATA_CLASSIFICATION:
				setDataClassification((String)newValue);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__COMPLIANCE_CHECKS:
				getComplianceChecks().clear();
				getComplianceChecks().addAll((Collection<? extends ComplianceCheckResult>)newValue);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__SOURCE_SYSTEM_COMPONENT:
				setSourceSystemComponent((String)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__MODEL_NAME:
				setModelName(MODEL_NAME_EDEFAULT);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__VERSION:
				setVersion(VERSION_EDEFAULT);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__STATUS:
				setStatus(STATUS_EDEFAULT);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__GENERATION_TIMESTAMP:
				setGenerationTimestamp(GENERATION_TIMESTAMP_EDEFAULT);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__GENERATED_BY:
				setGeneratedBy(GENERATED_BY_EDEFAULT);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__APPROVED_BY:
				setApprovedBy(APPROVED_BY_EDEFAULT);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DESCRIPTION:
				setDescription(DESCRIPTION_EDEFAULT);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__ATTRIBUTES:
				getAttributes().clear();
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DATA_OWNER:
				setDataOwner(DATA_OWNER_EDEFAULT);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DATA_CLASSIFICATION:
				setDataClassification(DATA_CLASSIFICATION_EDEFAULT);
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__COMPLIANCE_CHECKS:
				getComplianceChecks().clear();
				return;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__SOURCE_SYSTEM_COMPONENT:
				setSourceSystemComponent(SOURCE_SYSTEM_COMPONENT_EDEFAULT);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__MODEL_NAME:
				return MODEL_NAME_EDEFAULT == null ? modelName != null : !MODEL_NAME_EDEFAULT.equals(modelName);
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__VERSION:
				return VERSION_EDEFAULT == null ? version != null : !VERSION_EDEFAULT.equals(version);
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__STATUS:
				return status != STATUS_EDEFAULT;
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__GENERATION_TIMESTAMP:
				return GENERATION_TIMESTAMP_EDEFAULT == null ? generationTimestamp != null : !GENERATION_TIMESTAMP_EDEFAULT.equals(generationTimestamp);
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__GENERATED_BY:
				return GENERATED_BY_EDEFAULT == null ? generatedBy != null : !GENERATED_BY_EDEFAULT.equals(generatedBy);
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__APPROVED_BY:
				return APPROVED_BY_EDEFAULT == null ? approvedBy != null : !APPROVED_BY_EDEFAULT.equals(approvedBy);
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DESCRIPTION:
				return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__ATTRIBUTES:
				return attributes != null && !attributes.isEmpty();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DATA_OWNER:
				return DATA_OWNER_EDEFAULT == null ? dataOwner != null : !DATA_OWNER_EDEFAULT.equals(dataOwner);
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__DATA_CLASSIFICATION:
				return DATA_CLASSIFICATION_EDEFAULT == null ? dataClassification != null : !DATA_CLASSIFICATION_EDEFAULT.equals(dataClassification);
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__COMPLIANCE_CHECKS:
				return complianceChecks != null && !complianceChecks.isEmpty();
			case GovernancePackage.GOVERNANCE_DOCUMENTATION__SOURCE_SYSTEM_COMPONENT:
				return SOURCE_SYSTEM_COMPONENT_EDEFAULT == null ? sourceSystemComponent != null : !SOURCE_SYSTEM_COMPONENT_EDEFAULT.equals(sourceSystemComponent);
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (modelName: ");
		result.append(modelName);
		result.append(", version: ");
		result.append(version);
		result.append(", status: ");
		result.append(status);
		result.append(", generationTimestamp: ");
		result.append(generationTimestamp);
		result.append(", generatedBy: ");
		result.append(generatedBy);
		result.append(", approvedBy: ");
		result.append(approvedBy);
		result.append(", description: ");
		result.append(description);
		result.append(", dataOwner: ");
		result.append(dataOwner);
		result.append(", dataClassification: ");
		result.append(dataClassification);
		result.append(", sourceSystemComponent: ");
		result.append(sourceSystemComponent);
		result.append(')');
		return result.toString();
	}

} //GovernanceDocumentationImpl
