/**
 * Copyright (c) 2012 - 2026 Data In Motion and others.
 * All rights reserved.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Data In Motion - initial API and implementation
 */
package org.eclipse.fennec.model.atlas.bootstrap;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.Dictionary;
import java.util.HashSet;
import java.util.Hashtable;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import org.osgi.framework.BundleContext;
import org.osgi.framework.ServiceRegistration;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.ConfigurationPolicy;
import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;
import org.osgi.service.component.annotations.ReferenceCardinality;
import org.osgi.service.component.annotations.ReferencePolicy;
import org.osgi.service.component.annotations.ReferencePolicyOption;
import org.osgi.service.condition.Condition;
import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.Designate;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

/**
 * Registers the {@link Condition} {@value #CONDITION_ID} once every configured model
 * is registered, and withdraws it when one of them goes away.
 *
 * <p>
 * The {@link InitialModelLoader} requires this condition. It reads every seed file at
 * activation and resolves the whole folder before the packages get their nsURIs (issue
 * #339), so an instance whose EPackage ships in a bundle can only be read once that
 * bundle has registered it. Start levels do not say that: they order bundle starts, not
 * the Declarative Services components that register the packages, and the hand-written
 * runtimes assign none. A model bundle generated by Fennec EMF registers a
 * {@link Condition} with {@code osgi.condition.id} set to its nsURI as the last step
 * of its activation, after its EPackage; this component waits for those (issue #351).
 * </p>
 *
 * <p>
 * Without a configuration nothing is required and the condition is registered right
 * away, so a deployment that seeds no bundle-shipped model is not held back. A model
 * that never arrives keeps the loader from starting; after
 * {@code required.models.wait.seconds} the missing nsURIs are logged.
 * </p>
 */
@Component(name = RequiredModelsCondition.PID, immediate = true, configurationPolicy = ConfigurationPolicy.OPTIONAL)
@Designate(ocd = RequiredModelsCondition.Config.class)
public class RequiredModelsCondition {

    public static final String PID = "InitialModelLoaderRequiredModels";

    /** The {@code osgi.condition.id} of the condition this component registers. */
    public static final String CONDITION_ID = "atlas.initial.models.ready";

    private static final Logger LOG = System.getLogger(RequiredModelsCondition.class.getName());

    @ObjectClassDefinition(name = "Atlas Initial Model Loader Required Models")
    public @interface Config {

        @AttributeDefinition(name = "Required Models",
                description = "nsURIs of the bundle-shipped models the initial models refer to. The "
                        + "InitialModelLoader starts only once each of them has registered its condition "
                        + "(osgi.condition.id=<nsURI>).")
        String[] required_models() default {};

        @AttributeDefinition(name = "Required Models Wait Seconds",
                description = "After how many seconds the models still missing are logged as an error.")
        long required_models_wait_seconds() default 60;
    }

    private final Set<String> present = new HashSet<>();
    private final ScheduledExecutorService watchdog = Executors.newSingleThreadScheduledExecutor(r -> {
        Thread t = new Thread(r, "InitialModelLoader-required-models");
        t.setDaemon(true);
        return t;
    });
    private BundleContext bundleContext;
    private Set<String> required;
    private ServiceRegistration<Condition> registration;

    @Activate
    void activate(BundleContext bundleContext, Config config) {
        synchronized (present) {
            this.bundleContext = bundleContext;
            this.required = new LinkedHashSet<>(List.of(config.required_models()));
            update();
        }
        watchdog.schedule(this::logMissing, config.required_models_wait_seconds(), TimeUnit.SECONDS);
    }

    @Deactivate
    void deactivate() {
        watchdog.shutdownNow();
        synchronized (present) {
            unregister();
            bundleContext = null;
        }
    }

    @Reference(service = Condition.class, cardinality = ReferenceCardinality.MULTIPLE,
            policy = ReferencePolicy.DYNAMIC, policyOption = ReferencePolicyOption.GREEDY,
            target = "(!(" + Condition.CONDITION_ID + "=" + CONDITION_ID + "))")
    void bindCondition(Map<String, Object> properties) {
        conditionId(properties).ifPresent(id -> {
            synchronized (present) {
                present.add(id);
                update();
            }
        });
    }

    void unbindCondition(Map<String, Object> properties) {
        conditionId(properties).ifPresent(id -> {
            synchronized (present) {
                present.remove(id);
                update();
            }
        });
    }

    private static Optional<String> conditionId(Map<String, Object> properties) {
        return properties.get(Condition.CONDITION_ID) instanceof String id ? Optional.of(id)
                : Optional.empty();
    }

    /** Registers or withdraws the condition to match the models present. Called under {@link #present}. */
    private void update() {
        if (bundleContext == null) {
            // bound before activation; activate() decides
            return;
        }
        boolean ready = present.containsAll(required);
        if (ready && registration == null) {
            Dictionary<String, Object> properties = new Hashtable<>();
            properties.put(Condition.CONDITION_ID, CONDITION_ID);
            registration = bundleContext.registerService(Condition.class, Condition.INSTANCE, properties);
            LOG.log(Level.INFO, () -> "InitialModelLoader: required models present " + required);
        } else if (!ready && registration != null) {
            LOG.log(Level.WARNING, () -> "InitialModelLoader: required models missing " + missing()
                    + ", withdrawing " + CONDITION_ID);
            unregister();
        }
    }

    private void unregister() {
        if (registration != null) {
            try {
                registration.unregister();
            } catch (IllegalStateException e) {
                // already gone with the bundle
            }
            registration = null;
        }
    }

    private Set<String> missing() {
        Set<String> missing = new TreeSet<>(required);
        missing.removeAll(present);
        return missing;
    }

    private void logMissing() {
        synchronized (present) {
            if (registration == null && bundleContext != null) {
                LOG.log(Level.ERROR, () -> "InitialModelLoader: not started, still waiting for the models "
                        + missing() + " (configured in " + PID + ")");
            }
        }
    }
}
