<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mgmtapicurio" nsURI="http://eclipse.org/fennec/model/atlas/management/apicurio/1.0.0"
    nsPrefix="mgmtapicurio">
  <eAnnotations source="Version">
    <details key="value" value="1.0"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="complianceLevel" value="17.0"/>
    <details key="oSGiCompatible" value="true"/>
    <details key="basePackage" value="org.eclipse.fennec.model.atlas.mgmt"/>
    <details key="resource" value="XMI"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifactId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifactType" eType="#//ArtifactType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleArtifact" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//Content"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionedArtifact" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstVersion" eType="#//FirstVersion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FirstVersion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//Content"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArtifactType">
    <eLiterals name="XML"/>
    <eLiterals name="JSON" value="1"/>
    <eLiterals name="XSD" value="2"/>
  </eClassifiers>
</ecore:EPackage>
