/**
 * Copyright (c) 2012 - 2026 Data In Motion and others.
 * All rights reserved.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Data In Motion - initial API and implementation
 */
package org.eclipse.fennec.model.atlas.rest.client.osgi;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

/**
 * P6-6 — unit tests for the ConfigAdmin config property shapes generated by
 * {@link AtlasEPackageRegistryConfigurator}.
 * <p>
 * The static helpers are pure functions (no ConfigAdmin needed); the assertions
 * mirror the contract checked by SchemaRegistryChainConfiguratorIntegrationTest
 * on the server side, adapted for the client's {@code atlas.*} property filter.
 */
class AtlasEPackageRegistryConfiguratorTest {

	// ---- ePackageConfigurator.target ---------------------------------------

	@Test
	void ePackageConfiguratorTarget_withStage_filtersOnAtlasScopeAndStage() {
		String filter = AtlasEPackageRegistryConfigurator.ePackageConfiguratorTarget("jena", "snapshot");

		// Must use atlas.* properties — NOT emf.model.scope (server uses emf.model.scope;
		// client publications carry atlas.scope/atlas.stage instead).
		assertTrue(filter.contains("atlas.remote=true"), filter);
		assertTrue(filter.contains("atlas.scope=jena"), filter);
		assertTrue(filter.contains("atlas.stage=snapshot"), filter);
		// Must be an AND filter
		assertTrue(filter.startsWith("(&"), filter);
	}

	@Test
	void ePackageConfiguratorTarget_withoutStage_excludesAtlasStageProperty() {
		String filter = AtlasEPackageRegistryConfigurator.ePackageConfiguratorTarget("jena", null);

		assertTrue(filter.contains("atlas.remote=true"), filter);
		assertTrue(filter.contains("atlas.scope=jena"), filter);
		// Negation of atlas.stage is present to avoid matching staged services.
		// The filter contains (!(atlas.stage=*)), not a positive (atlas.stage=X) clause.
		assertTrue(filter.contains("!(atlas.stage="), filter);
	}

	// ---- parentRegistry.target (fetch-on-miss bridge filter) ---------------

	@Test
	void fetchOnMissTarget_withStage_pointsToScopedBridgeService() {
		String filter = AtlasEPackageRegistryConfigurator.fetchOnMissTarget("jena", "snapshot");

		assertTrue(filter.contains("atlas.scope=jena"), filter);
		assertTrue(filter.contains("atlas.stage=snapshot"), filter);
		assertTrue(filter.contains(AtlasScopedFetchOnMissRegistry.FETCH_ON_MISS_PROPERTY + "=true"), filter);
	}

	@Test
	void fetchOnMissTarget_withoutStage_excludesStagedBridgeServices() {
		String filter = AtlasEPackageRegistryConfigurator.fetchOnMissTarget("jena", null);

		assertTrue(filter.contains("atlas.scope=jena"), filter);
		assertTrue(filter.contains(AtlasScopedFetchOnMissRegistry.FETCH_ON_MISS_PROPERTY + "=true"), filter);
		// Filter must negate atlas.stage so it only matches the stage-free bridge,
		// not staged bridges registered for the same scope.
		assertTrue(filter.contains("!(atlas.stage="), filter);
	}

	// ---- rsf.name ----------------------------------------------------------

	@Test
	void rsfName_withStage_usesScopeUnderscoreStage() {
		assertEquals("jena_snapshot", AtlasEPackageRegistryConfigurator.rsfName("jena", "snapshot"));
	}

	@Test
	void rsfName_withoutStage_usesScopeOnly() {
		assertEquals("jena", AtlasEPackageRegistryConfigurator.rsfName("jena", null));
	}
}
